AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution with AWS WAFv2 WebACL protecting an ALB origin

Parameters:
  ALBDomainName:
    Description: The DNS name of your Application Load Balancer (e.g. k8s-bookstor-ecommerc-9822864267-940650448.us-east-1.elb.amazonaws.com)
    Type: String
  ACMCertificateArn:
    Description: ARN of the ACM certificate in us-east-1 for your domain (required for HTTPS in CloudFront)
    Type: String

Resources:

  # WAFv2 Web ACL with AWS Managed Rules
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: cloudfront-waf-webacl
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: cloudfront-waf-webacl
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: alb-origin
            DomainName: !Ref ALBDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          Compress: true
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: sni-only
        PriceClass: PriceClass_100
        WebACLId: !GetAtt WebACL.Arn
        HttpVersion: http2
        Enabled: true

Outputs:
  CloudFrontDomainName:
    Description: The domain name of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebACLArn:
    Description: ARN of the WAFv2 WebACL
    Value: !GetAtt WebACL.Arn
