---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for ecommerce app images.

Parameters:
  BucketName:
    Description: Unique bucket name for images
    Type: String
    Default: ecommerce-images-<your-unique-id>

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
